spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #配置当前要使用的数据源的操作类型那个
    driver-class-name: com.mysql.jdbc.Driver       #配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/vuelearn?useUnicode=true&characterEncoding=utf8
    username: ccc
    password: 12312

server:
  port: 8081

mybatis-plus:
  # xml
  mapper-locations: classpath:mapper/*Mapper.xml
# 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.vuelearn.pro.mapper
  configuration:
      # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
